/**
 * Design Library — DESIGN.md serializer tests (Phase D2).
 *
 * Locks two invariants:
 *
 *   1. GOLDEN SHAPE — the serializer emits exactly the 5-section
 *      DESIGN.md body the D4 gallery renderer expects. A sloppy edit
 *      that drops a section, reorders bullets, or drifts the footer
 *      format will break the snapshot and force a conscious update.
 *
 *   2. ROUND-TRIP CONSISTENCY — feeding the serializer's output back
 *      through D1's `extractTitleAndSummary()` must yield the SAME
 *      `title` + `summary` the serializer returned. The gallery card
 *      (which reads the DB row and re-parses) will then render the
 *      same text the clone-pro pipeline stamped at write time.
 *
 * The tests use a frozen `clonedAt` date so the ISO-day footer line
 * is deterministic. Real callers let `clonedAt` default to `new Date()`.
 */

import { describe, expect, it } from 'vitest'
import type { ExtractedDesign } from '../clone-pro/types.js'
import { serializeCloneDesign } from './serialize-design-md.js'
import { extractTitleAndSummary } from './parse-design-md.js'

// ---------------------------------------------------------------------------
// Fixture builders
// ---------------------------------------------------------------------------

/**
 * Build a realistic ExtractedDesign for tests. Defaults mirror a
 * typical modern brand site (Airbnb-shaped palette, Inter/Circular
 * typography). Pass `overrides` to poke specific fields.
 */
function makeDesign(overrides: Partial<ExtractedDesign> = {}): ExtractedDesign {
  return {
    palette: {
      primary: '#FF5A5F',
      secondary: '#00A699',
      accent: '#FC642D',
      background: '#FFFFFF',
      surface: '#F7F7F7',
      text: '#484848',
      textMuted: '#767676',
      border: '#EBEBEB',
      success: '#008A05',
      error: '#C13515',
      warning: '#FFB400',
    },
    typography: {
      headingFamily: 'Circular, sans-serif',
      bodyFamily: 'Inter, sans-serif',
      headingWeight: '700',
      bodyWeight: '400',
      baseSize: '16px',
      lineHeight: '1.5',
      googleFontsUrls: ['https://fonts.googleapis.com/css2?family=Circular'],
    },
    layout: {
      maxWidth: '1280px',
      containerPadding: '24px',
      sectionGap: '96px',
      gridColumns: 12,
      hasAnnouncement: false,
      hasStickyHeader: true,
      hasHero: true,
      hasMegaMenu: false,
      footerColumns: 4,
    },
    sections: [
      { type: 'header', position: 0, estimatedHeight: '80px', classes: ['nav'] },
      {
        type: 'hero',
        position: 1,
        estimatedHeight: '600px',
        classes: ['hero'],
        aiDescription: 'Large photo-forward hero',
      },
      { type: 'feature-grid', position: 2, estimatedHeight: 'auto', classes: ['features'] },
    ],
    style: 'modern',
    ...overrides,
  }
}

/** Frozen clone timestamp so golden snapshots don't drift day-to-day. */
const CLONED_AT = new Date('2026-04-18T12:00:00Z')

// ---------------------------------------------------------------------------
// Golden snapshot — the canonical shape the D4 gallery expects.
// ---------------------------------------------------------------------------

describe('serializeCloneDesign — golden shape', () => {
  it('produces the exact DESIGN.md body for a realistic clone', () => {
    const result = serializeCloneDesign({
      design: makeDesign(),
      sourceUrl: 'https://www.airbnb.com/',
      clonedAt: CLONED_AT,
    })

    const expected = [
      '# Airbnb.com',
      '',
      'A **modern** design cloned from airbnb.com with a 11-color palette anchored by `#FF5A5F`. 3 sections detected.',
      '',
      '## 1. Visual Theme',
      '',
      'Classification: **modern**. Source: `https://www.airbnb.com/`.',
      '',
      '- Hero section present above the fold',
      '- Sticky header pattern',
      '',
      '## 2. Colors',
      '',
      '- Primary: `#FF5A5F`',
      '- Secondary: `#00A699`',
      '- Accent: `#FC642D`',
      '- Background: `#FFFFFF`',
      '- Surface: `#F7F7F7`',
      '- Text: `#484848`',
      '- Text muted: `#767676`',
      '- Border: `#EBEBEB`',
      '- Success: `#008A05`',
      '- Warning: `#FFB400`',
      '- Error: `#C13515`',
      '',
      '## 3. Typography',
      '',
      '- Body: `Inter, sans-serif`, weight 400, 16px/1.5',
      '- Heading: `Circular, sans-serif`, weight 700',
      '- Google Fonts URLs: 1',
      '',
      '## 4. Layout',
      '',
      '- Max content width: `1280px`',
      '- Container padding: `24px`',
      '- Section gap: `96px`',
      '- Grid columns: 12',
      '- Footer columns: 4',
      '',
      '## 5. Sections Detected',
      '',
      '1. header — h≈80px',
      '2. hero — h≈600px; Large photo-forward hero',
      '3. feature-grid',
      '',
      '---',
      '_Generated by gbox-platform clone-pro on 2026-04-18 from `https://www.airbnb.com/`._',
      '', // trailing newline — `lines.join('\n') + '\n'`
    ].join('\n')

    expect(result.designMd).toBe(expected)
  })

  it('returns the stripped title as the H1 text (no markdown prefixes)', () => {
    const { title } = serializeCloneDesign({
      design: makeDesign(),
      sourceUrl: 'https://www.airbnb.com/',
      clonedAt: CLONED_AT,
    })
    expect(title).toBe('Airbnb.com')
  })

  it('returns the stripped lead paragraph as the summary (no ** or `)', () => {
    const { summary } = serializeCloneDesign({
      design: makeDesign(),
      sourceUrl: 'https://www.airbnb.com/',
      clonedAt: CLONED_AT,
    })
    expect(summary).toBe(
      'A modern design cloned from airbnb.com with a 11-color palette anchored by #FF5A5F. 3 sections detected.',
    )
  })

  it('footer line carries the ISO day of clonedAt (UTC)', () => {
    // Passing a late-afternoon US/Pacific time translates to the
    // following UTC day — guard against accidental local-time slicing.
    const { designMd } = serializeCloneDesign({
      design: makeDesign(),
      sourceUrl: 'https://example.com',
      clonedAt: new Date('2026-04-18T23:30:00-07:00'), // = 2026-04-19T06:30Z
    })
    expect(designMd).toMatch(/on 2026-04-19 from `https:\/\/example\.com`/)
  })
})

// ---------------------------------------------------------------------------
// Round-trip — serializer output parses back to the same title + summary.
// ---------------------------------------------------------------------------

describe('serializeCloneDesign — round-trip with parse-design-md', () => {
  it('parser extracts the same title the serializer returned', () => {
    const { designMd, title } = serializeCloneDesign({
      design: makeDesign(),
      sourceUrl: 'https://www.airbnb.com/',
      clonedAt: CLONED_AT,
    })
    const { title: reParsed } = extractTitleAndSummary(designMd, 'airbnb.com')
    expect(reParsed).toBe(title)
  })

  it('parser extracts the same summary the serializer returned', () => {
    const { designMd, summary } = serializeCloneDesign({
      design: makeDesign(),
      sourceUrl: 'https://www.airbnb.com/',
      clonedAt: CLONED_AT,
    })
    const { summary: reParsed } = extractTitleAndSummary(designMd, 'airbnb.com')
    expect(reParsed).toBe(summary)
  })

  it('round-trip survives an override displayTitle too', () => {
    const { designMd, title } = serializeCloneDesign({
      design: makeDesign(),
      sourceUrl: 'https://d1234abcd.cloudfront.net/',
      clonedAt: CLONED_AT,
      displayTitle: 'Stripe (demo mirror)',
    })
    const { title: reParsed } = extractTitleAndSummary(designMd, 'mirror')
    expect(title).toBe('Stripe (demo mirror)')
    expect(reParsed).toBe('Stripe (demo mirror)')
  })
})

// ---------------------------------------------------------------------------
// Edge cases — shape under partial/degenerate ExtractedDesign.
// ---------------------------------------------------------------------------

describe('serializeCloneDesign — edge cases', () => {
  it('emits a "None detected" line when sections is empty', () => {
    const { designMd } = serializeCloneDesign({
      design: makeDesign({ sections: [] }),
      sourceUrl: 'https://example.com',
      clonedAt: CLONED_AT,
    })
    expect(designMd).toMatch(
      /## 5\. Sections Detected\n\n_None detected — rule-based parser \+ AI fallback both returned empty\._/,
    )
  })

  it('drops the section count clause from the lead paragraph when empty', () => {
    const { summary } = serializeCloneDesign({
      design: makeDesign({ sections: [] }),
      sourceUrl: 'https://example.com',
      clonedAt: CLONED_AT,
    })
    // The trailing " N sections detected." sentence is omitted when
    // there's nothing to report. The rest of the lead stays intact.
    expect(summary).toMatch(
      /^A modern design cloned from example\.com with a 11-color palette anchored by #FF5A5F\.$/,
    )
  })

  it('singularises "1 section" (not "1 sections")', () => {
    const { summary } = serializeCloneDesign({
      design: makeDesign({
        sections: [
          { type: 'header', position: 0, estimatedHeight: '80px', classes: [] },
        ],
      }),
      sourceUrl: 'https://example.com',
      clonedAt: CLONED_AT,
    })
    expect(summary).toContain('1 section detected.')
    expect(summary).not.toContain('1 sections')
  })

  it('omits the Google Fonts URLs line when no fonts detected', () => {
    const { designMd } = serializeCloneDesign({
      design: makeDesign({
        typography: {
          ...makeDesign().typography,
          googleFontsUrls: [],
        },
      }),
      sourceUrl: 'https://example.com',
      clonedAt: CLONED_AT,
    })
    expect(designMd).not.toMatch(/Google Fonts URLs/)
  })

  it('emits "(No layout flags detected)" when all 4 boolean flags are false', () => {
    const { designMd } = serializeCloneDesign({
      design: makeDesign({
        layout: {
          ...makeDesign().layout,
          hasHero: false,
          hasStickyHeader: false,
          hasAnnouncement: false,
          hasMegaMenu: false,
        },
      }),
      sourceUrl: 'https://example.com',
      clonedAt: CLONED_AT,
    })
    expect(designMd).toMatch(/- \(No layout flags detected\)/)
  })

  it('emits "(No colors detected)" when the palette is entirely blank', () => {
    const emptyPalette = {
      primary: '',
      secondary: '',
      accent: '',
      background: '',
      surface: '',
      text: '',
      textMuted: '',
      border: '',
      success: '',
      error: '',
      warning: '',
    }
    const { designMd, summary } = serializeCloneDesign({
      design: makeDesign({ palette: emptyPalette }),
      sourceUrl: 'https://example.com',
      clonedAt: CLONED_AT,
    })
    expect(designMd).toMatch(/## 2\. Colors\n\n- \(No colors detected\)/)
    // `#000000` is the documented fallback when primary is missing so the
    // lead paragraph still reads as a full sentence.
    expect(summary).toContain('anchored by #000000')
    expect(summary).toContain('0-color palette')
  })

  it('only emits palette entries that are non-empty (skips blank slots)', () => {
    const { designMd, summary } = serializeCloneDesign({
      design: makeDesign({
        palette: {
          primary: '#FF5A5F',
          secondary: '',
          accent: '',
          background: '#FFFFFF',
          surface: '',
          text: '',
          textMuted: '',
          border: '',
          success: '',
          error: '',
          warning: '',
        },
      }),
      sourceUrl: 'https://example.com',
      clonedAt: CLONED_AT,
    })
    expect(designMd).toMatch(/- Primary: `#FF5A5F`/)
    expect(designMd).toMatch(/- Background: `#FFFFFF`/)
    expect(designMd).not.toMatch(/- Secondary:/)
    expect(designMd).not.toMatch(/- Surface:/)
    expect(summary).toContain('2-color palette')
  })

  it('skips the h≈ extra for sections with estimatedHeight "auto"', () => {
    const { designMd } = serializeCloneDesign({
      design: makeDesign({
        sections: [
          { type: 'footer', position: 0, estimatedHeight: 'auto', classes: [] },
        ],
      }),
      sourceUrl: 'https://example.com',
      clonedAt: CLONED_AT,
    })
    // The section line should have no " — " extras because the only
    // candidate was auto (skipped) and there's no aiDescription.
    expect(designMd).toMatch(/1\. footer\n/)
    expect(designMd).not.toMatch(/1\. footer — /)
  })

  it('keeps aiDescription on the section line even when height is auto', () => {
    const { designMd } = serializeCloneDesign({
      design: makeDesign({
        sections: [
          {
            type: 'testimonials',
            position: 0,
            estimatedHeight: 'auto',
            classes: [],
            aiDescription: 'Three customer quotes in a row',
          },
        ],
      }),
      sourceUrl: 'https://example.com',
      clonedAt: CLONED_AT,
    })
    expect(designMd).toMatch(
      /1\. testimonials — Three customer quotes in a row/,
    )
  })

  it('falls back to manual hostname parse when URL() rejects the source', () => {
    // Missing protocol — `new URL()` throws, serializer's catch path
    // must still pull a usable hostname out for the H1 and lead.
    const { title, summary } = serializeCloneDesign({
      design: makeDesign(),
      sourceUrl: 'www.clay.com/pricing?ref=hn',
      clonedAt: CLONED_AT,
    })
    expect(title).toBe('Clay.com')
    expect(summary).toContain('cloned from clay.com')
  })

  it('uses displayTitle verbatim when provided (overrides hostname)', () => {
    const { title, designMd } = serializeCloneDesign({
      design: makeDesign(),
      sourceUrl: 'https://d1234abcd.cloudfront.net/',
      clonedAt: CLONED_AT,
      displayTitle: 'Acme Co',
    })
    expect(title).toBe('Acme Co')
    expect(designMd.startsWith('# Acme Co\n')).toBe(true)
  })

  it('falls back to "Clone" when both sourceUrl and displayTitle are empty', () => {
    const { title } = serializeCloneDesign({
      design: makeDesign(),
      sourceUrl: '',
      clonedAt: CLONED_AT,
    })
    // Belt-and-braces — caller pipeline already validates URLs, so this
    // branch shouldn't trigger in production.
    expect(title).toBe('Clone')
  })
})
