/**
 * Gbox Platform — Gbox Dawn bundle (public API)
 *
 * Decision #1 Step 1.17c. Re-exports the build-time generated
 * `GBOX_DAWN_BUNDLE` map plus a small set of accessor helpers so
 * callers don't have to import the generated file directly. The
 * generated file is regenerated by
 *
 *     npx tsx scripts/generate-gbox-dawn-bundle.ts
 *
 * after any edit to `seed/gbox-dawn/**`.
 *
 * Why a separate public module instead of importing the generated
 * file everywhere?
 *
 *   - The generated file is one giant `Map` literal — easier to keep
 *     it dumb and put the policy (sorting, filtering, validation,
 *     iteration helpers) in a hand-written module that wraps it.
 *
 *   - Tests can stub the public API in isolation without depending
 *     on the generated file's exact shape.
 *
 *   - Worker bundles only have to tree-shake one entry point.
 */

import {
  GBOX_DAWN_BUNDLE,
  GBOX_DAWN_BUNDLE_VERSION,
  type GboxDawnAsset,
} from './gbox-dawn-bundle.generated.js'

export {
  GBOX_DAWN_BUNDLE,
  GBOX_DAWN_BUNDLE_VERSION,
  type GboxDawnAsset,
}

/**
 * Number of files in the bundle. Useful for sanity tests + CLI
 * "did the generator run?" checks.
 */
export function gboxDawnBundleSize(): number {
  return GBOX_DAWN_BUNDLE.size
}

/**
 * Iterate the bundle as an array of `GboxDawnAsset` entries, sorted
 * by key for stable iteration order. The underlying `Map` already
 * preserves insertion order (the generator sorts before writing) but
 * this helper makes the contract explicit at every callsite.
 */
export function listGboxDawnAssets(): readonly GboxDawnAsset[] {
  return [...GBOX_DAWN_BUNDLE.values()].sort((a, b) =>
    a.key.localeCompare(b.key),
  )
}

/**
 * Look up a single asset by its theme-relative key. Returns
 * `undefined` when the key is unknown — callers can decide whether
 * that is a programming error or a soft miss.
 */
export function getGboxDawnAsset(key: string): GboxDawnAsset | undefined {
  return GBOX_DAWN_BUNDLE.get(key)
}

/**
 * Filter the bundle by a key prefix. Used by the install helper to
 * "install everything in `sections/`" or "install everything in
 * `locales/`" without inspecting individual entries. Always returns
 * the matching subset sorted by key.
 */
export function filterGboxDawnAssetsByPrefix(
  prefix: string,
): readonly GboxDawnAsset[] {
  return listGboxDawnAssets().filter((a) => a.key.startsWith(prefix))
}
