#!/usr/bin/env bash
# ============================================================================
# Gbox Platform — SSL/TLS Setup for Production
#
# Issues a wildcard certificate via Let's Encrypt (DNS-01 challenge)
# or individual certs via HTTP-01 for each subdomain.
#
# Usage:
#   sudo bash scripts/setup-ssl-production.sh gbox.co             # production
#   sudo bash scripts/setup-ssl-production.sh gbox.co --wildcard  # wildcard cert
#
# Prerequisites:
#   apt install certbot python3-certbot-nginx -y
# ============================================================================
set -euo pipefail

DOMAIN="${1:?Usage: $0 <domain> [--wildcard]}"
WILDCARD="${2:-}"
TAG="ssl-setup"

log() { echo "[$TAG] $*"; }
die() { echo "[$TAG] ERROR: $*" >&2; exit 1; }

# Check certbot
command -v certbot >/dev/null 2>&1 || die "certbot not found. Install: apt install certbot python3-certbot-nginx -y"

# Subdomains we need certs for
SUBDOMAINS=(
  "$DOMAIN"
  "www.$DOMAIN"
  "checkout.$DOMAIN"
  "api.$DOMAIN"
  "admin.$DOMAIN"
  "accounts.$DOMAIN"
)

if [[ "$WILDCARD" == "--wildcard" ]]; then
  # ---- Wildcard cert (requires DNS-01 challenge) ----
  log "Requesting wildcard certificate for *.$DOMAIN"
  log "NOTE: This requires DNS TXT record validation."
  log "You'll need to add a TXT record when prompted."
  echo ""

  certbot certonly \
    --manual \
    --preferred-challenges dns \
    -d "$DOMAIN" \
    -d "*.$DOMAIN" \
    --agree-tos \
    --no-eff-email \
    -m "admin@$DOMAIN"

  CERT_PATH="/etc/letsencrypt/live/$DOMAIN"

else
  # ---- Individual certs (HTTP-01 — simpler, no DNS access needed) ----
  log "Requesting individual certificates for all subdomains..."

  # Build -d flags
  DOMAIN_FLAGS=""
  for sub in "${SUBDOMAINS[@]}"; do
    DOMAIN_FLAGS="$DOMAIN_FLAGS -d $sub"
  done

  certbot --nginx \
    $DOMAIN_FLAGS \
    --agree-tos \
    --no-eff-email \
    -m "admin@$DOMAIN" \
    --redirect

  CERT_PATH="/etc/letsencrypt/live/$DOMAIN"
fi

# ---- Post-install: update nginx for HTTPS ----
log "Certificate issued at $CERT_PATH"

# Add HSTS and modern TLS to nginx
NGINX_SSL_CONF="/etc/nginx/conf.d/ssl-params.conf"
cat > "$NGINX_SSL_CONF" << 'SSL_CONF'
# Gbox Platform — SSL Parameters (shared across server blocks)
# Generated by setup-ssl-production.sh

# Modern TLS configuration
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;

# SSL session cache
ssl_session_cache shared:SSL:50m;
ssl_session_timeout 1d;
ssl_session_tickets off;

# OCSP stapling
ssl_stapling on;
ssl_stapling_verify on;
resolver 8.8.8.8 8.8.4.4 valid=300s;
resolver_timeout 5s;

# DH parameters (generate: openssl dhparam -out /etc/nginx/dhparam.pem 2048)
# ssl_dhparam /etc/nginx/dhparam.pem;
SSL_CONF

log "SSL params written to $NGINX_SSL_CONF"

# ---- Setup auto-renewal cron ----
if ! crontab -l 2>/dev/null | grep -q 'certbot renew'; then
  log "Adding certbot auto-renewal cron (daily at 3:30 AM)"
  (crontab -l 2>/dev/null; echo "30 3 * * * certbot renew --quiet --post-hook 'systemctl reload nginx'") | crontab -
fi

# Test and reload
log "Testing nginx..."
nginx -t && systemctl reload nginx

echo ""
log "SSL setup complete for $DOMAIN"
echo ""
echo "  Secured domains:"
for sub in "${SUBDOMAINS[@]}"; do
  echo "    https://$sub"
done
echo ""
echo "  Auto-renewal: daily at 3:30 AM (cron)"
echo "  Cert path:    $CERT_PATH"
